name: Notify regarding games

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # We'll run this daily at noon.
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  runner-job:
    runs-on: ubuntu-20.04
    steps:
      # Shallow should be fine for video
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
            pip install -r requirements.txt
            pip install awscli
      - name: Run
        run: |
            python what2watch.py
            git add data/
            git commit -a -m 'Automated commit'
            git push
            aws ses send-email --destination "ToAddresses=${DISTRIBUTION_LIST}" --from helena@galaxians.org --subject 'MLB: What2Watch' --html "$(python what2watch.py --html)"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SES_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: eu-central-1
          DISTRIBUTION_LIST: ${{ secrets.DISTRIBUTION_LIST }}
